-- DAPNET Core Table Creation
-- Version 1.0 2018-02-26

DROP TABLE IF EXISTS users;
CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	is_admin BOOLEAN NOT NULL,
	is_enabled BOOLEAN NOT NULL,
	created_on DATETIME NOT NULL,
	last_login DATETIME
);

DROP TABLE IF EXISTS nodes;
CREATE TABLE nodes(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(50) NOT NULL UNIQUE,
	status VARCHAR(20) NOT NULL,
	last_update DATETIME
);

DROP TABLE IF EXISTS pagers;
CREATE TABLE pagers(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	number INT NOT NULL UNIQUE,
	name VARCHAR(20) NOT NULL,
	type VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS callsigns;
CREATE TABLE callsigns(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(20) NOT NULL UNIQUE,
	description VARCHAR(100)
);

DROP TABLE IF EXISTS calls;
CREATE TABLE calls(
	id LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
	text VARCHAR(100) NOT NULL,
	posted_on DATETIME NOT NULL,
	is_emergency BOOLEAN NOT NULL
);

DROP TABLE IF EXISTS rubrics;
CREATE TABLE rubrics(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	number INT NOT NULL,
	name VARCHAR(20) NOT NULL,
	label VARCHAR(11) NOT NULL
);

DROP TABLE IF EXISTS news;
CREATE TABLE news(
	id LONG AUTO_INCREMENT PRIMARY KEY NOT NULL,
	text VARCHAR(100) NOT NULL,
	posted_on DATETIME NOT NULL,
	number INT NOT NULL
);

DROP TABLE IF EXISTS transmitters;
CREATE TABLE transmitters(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(20) NOT NULL UNIQUE,
	auth_key VARCHAR(64) NOT NULL
);

DROP TABLE IF EXISTS transmitter_groups;
CREATE TABLE transmitter_groups(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(20) NOT NULL UNIQUE,
	description VARCHAR(100)
);
